version: '3.7'

services:
  executor:
    build:
      context: executor
      args:
        CERT_PASS: ${CERT_PASS}
    image: executor:1.0
    container_name: executor
    user: 1000:1000
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      CERT_PASS: ${CERT_PASS}
      KAFKA_EXECUTOR_HOST: ${KAFKA_EXECUTOR_HOST}
      KAFKA_EXECUTOR_PORT: ${KAFKA_EXECUTOR_PORT}
      KAFKA_EXECUTOR_SCHEMA_REGISTRY_HOST: ${KAFKA_EXECUTOR_SCHEMA_REGISTRY_HOST}
      KAFKA_EXECUTOR_SCHEMA_REGISTRY_PORT: ${KAFKA_EXECUTOR_SCHEMA_REGISTRY_PORT}
      KAFKA_EXECUTOR_SCHEMA_REGISTRY_USER: ${KAFKA_EXECUTOR_SCHEMA_REGISTRY_USER}
      KAFKA_EXECUTOR_SCHEMA_REGISTRY_PASSWORD: ${KAFKA_EXECUTOR_SCHEMA_REGISTRY_PASSWORD}
      JAVA_OPTS: >-
        -Xms1g -Xmx1g
      #  -Djasypt.encryptor.password=${JASYPT_PASS}
      #  -Dspring.datasource.url=jdbc:mariadb://rccdb:3306/${MARIADB_DATABASE}
      #  -Dspring.datasource.username=${MARIADB_USER}
      #  -Dspring.datasource.password=${MARIADB_PASSWORD}
      TZ: America/New_York

  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: node-exporter
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    environment:
      TZ: America/New_York

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    expose:
      - 9090
    environment:
          TZ: America/New_York
